### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by younes200** [marcbelmont/cnn-watermark-removal#5]
Hi Marc,
First of all, thanks for sharing the experiment it's pretty interesting for learning.
I had few questions tho, the selection file must be with the same width/height than the input image ? the Training tooks hours and reach 40000 epoch but with this result :
![output](https://user-images.githubusercontent.com/198514/34453785-7ade4c52-ed54-11e7-8f8c-1d9013306ef8.png)
Her is also my model :
[data.zip](https://github.com/marcbelmont/cnn-watermark-removal/files/1594328/data.zip)

Thank you.

**Comment by marcbelmont** [comment]
I have updated the example image. It turns out the one I initially provided is not close enough to the training set (the way the overlay was applied was too different from the way the overlay is applied during training).

You should now get the following with your weights:
![image](https://user-images.githubusercontent.com/45101/35271629-fb53ac06-0032-11e8-84b7-4f98bb71d9fc.png)
